### ISSUE TITLE
Nothing can be created. Not a single item can be dragged and dropped.

### ISSUE THREAD

**Issue by piiskop** [jgraph/drawio-nextcloud#54] opened 2023-07-27 23:53 UTC
I just switched the app on after upgrading it and not a single element can be dragged and dropped. How is this app meant to be used? I have the newest Nextcloud, too.

**Comment by arnowelzel** [comment] 2023-08-03 12:56
This only happens for new diagrams. Just close the diagram and open it again, then you can edit it.

**Comment by piiskop** [comment] 2023-08-04 06:19
Yes. Also, refresh helps which means reopening. Is this normal?

**Comment by davidjgraph** [comment] 2023-08-04 09:40
Marking as duplicate of #57 as description of this issue unclear.

**Closed by davidjgraph** 2023-08-04 09:40 UTC
Labels: low quality
