### ISSUE TITLE
.drawio file gets downloaded instead of opened in Chrome

### ISSUE THREAD

**Issue by maximelehericy** [jgraph/drawio-nextcloud#53] opened 2023-07-27 11:38 UTC
.drawio file gets downloaded instead of opened in Chrome

in Firefox, .drawio file is opened in the browser window.

NC 27.0.1
Drawio app 2.1.2

**Comment by m-mohamedin** [comment] 2024-01-01 23:51
We cannot reproduce, is it still an issue with the latest version?

**Comment by maximelehericy** [comment] 2024-01-03 15:10
Hi @m-mohamedin 
I just reproduce the error under:
- Chromium (Version 120.0.6099.129 (Official Build) Fedora Project (64-bit))
- NC 27.1.5 
- drawio app 2.1.4

**Comment by GreenCappuccino** [comment] 2024-01-08 17:26
I used to have this issue on Files for NC27, on NC28 this issue has been resolved for me. For the record this only happened for me on Edge when opening the file from the Dashboard overview. Directly navigating to the directory and clicking on the link opened the editor properly. I assume this is related to Files.

**Comment by davidjgraph** [comment] 2024-01-08 17:47
If nobody can reproduce on NC 28 I'll close this up. If you do see it on 28 shout in a comment.

**Closed by davidjgraph** 2024-01-08 17:47 UTC
